#!/bin/bash

set -e

if [ -z $1 ]; then
  echo "Please set the 'version' variable"
  exit 1
fi

VERSION="$1"

# the temp folder to store binary file...
mkdir -p binary
rm -rf binary/* || true

cd `dirname $0`

# the temp folder to store distribution source code...
TEMP=`mktemp -d ${TMPDIR-/tmp}/distribution.XXXXXX`
git clone -b $VERSION --depth 1 https://github.com/distribution/distribution.git $TEMP

# add patch redis
cd $TEMP
git apply ~-/redis.patch
cd -

echo 'build the registry binary ...'
for arch in amd64 arm64; do
	docker build -f Dockerfile.binary --build-arg GOARCH=$arch -o binary/$arch/ $TEMP
done

echo "Build registry binary success, then to build photon image..."
cp $TEMP/cmd/registry/config-example.yml config.yml
rm -rf $TEMP
