#!/bin/bash

set +e

if [ -z $1 ]; then
  error "Please set the 'version' variable"
  exit 1
fi

VERSION="$1"

set -e

# the temp folder to store binary file...
mkdir -p binary
rm -rf binary/*

cd `dirname $0`
cur=$PWD

# the temp folder to store distribution source code...
TEMP=`mktemp -d ${TMPDIR-/tmp}/distribution.XXXXXX`
git clone -b $VERSION https://github.com/distribution/distribution.git $TEMP

# add patch redis
cd $TEMP
git apply $cur/redis.patch
cd $cur
cp Dockerfile.binary $TEMP

for arch in amd64 arm64; do
	echo 'build the registry binary ...'
	docker build -f $TEMP/Dockerfile.binary -t registry-golang --build-arg GOARCH=$arch $TEMP

	echo 'copy the registry binary to local...'
	ID=$(docker create registry-golang)
	mkdir binary/$arch
	docker cp $ID:/go/src/github.com/docker/distribution/bin/registry binary/$arch/registry

	docker rm -f $ID
	docker rmi -f registry-golang
done

echo "Build registry binary success, then to build photon image..."
cd $cur
cp $TEMP/cmd/registry/config-example.yml config.yml
rm -rf $TEMP
